<?php
$z[0]=Array("field","",162,191);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",322,353);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",482,514);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",675,820);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[4]=Array("arclist","\r\n      <div data-type=\"list_113\" >\r\n        <div class=\"widget widget-shadow\">\r\n          <figure class=\"widget-header cover\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>\r\n            <div class=\"mask\"> </div>\r\n            <img class=\"img-responsive\" alt=\"[field:title/]\" src=\"[field:picname/]\"/> </a> </figure>\r\n          <h4 class=\"widget-title\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>[field:title/]</a>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n          </h4>\r\n        </div>\r\n      </div>\r\n      ",1015,1656);
$z[4][4]=array();
$z[4][4]['titlelen']="80";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("channelartlist","\r\n<div class=\"met-index-news met-index-body\">\r\n  <div class=\"container\">\r\n    <h3 class=\"invisible\" data-plugin=\"appear\" data-animate=\"fade\" data-repeat=\"false\">{dede:field name='typename'",1682,1907);
$z[5][4]=array();
$z[5][4]['typeid']="11,0";
$z[6]=Array("field","",2038,2069);
$z[6][4]=array();
$z[6][4]['name']="typenameen";
$z[7]=Array("field","",2199,2231);
$z[7][4]=array();
$z[7][4]['name']="description";
$z[8]=Array("arclist","\r\n      <li class=\"invisible animation-delay-300\" data-plugin=\"appear\" data-animate=\"fadeInRight\" data-repeat=\"false\">\r\n        <div class=\"media media-lg\">\r\n          <div class=\"media-body\">\r\n            <h4 class=\"media-heading\"> <span class=\"news_time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self' > [field:title/]</a> </h4>\r\n            <p class=\"des\">[field:description function=\"cn_substr(@me,180)\"/]...</p>\r\n            <p class=\"info\"> </p>\r\n          </div>\r\n        </div>\r\n      </li>\r\n      ",2287,2933);
$z[8][4]=array();
$z[8][4]['titlelen']="80";
$z[8][4]['orderby']="pubdate";
$z[8][4]['row']="6";
$z[9]=Array("field","",2959,2987);
$z[9][4]=array();
$z[9][4]['name']="typeurl";
$z[10]=Array("field","",3010,3039);
$z[10][4]=array();
$z[10][4]['name']="typename";

?>