<?php
$z[0]=Array("field","",159,188);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",319,350);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",480,512);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","\r\n      <li class=\"invisible animation-delay-300\" data-plugin=\"appear\" data-animate=\"fadeInRight\" data-repeat=\"false\">\r\n        <div class=\"media media-lg\">\r\n          <div class=\"media-body\">\r\n            <h4 class=\"media-heading\"> <span class=\"news_time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self' > [field:title/]</a> </h4>\r\n            <p class=\"des\">[field:description function=\"cn_substr(@me,180)\"/]...</p>\r\n            <p class=\"info\"> </p>\r\n          </div>\r\n        </div>\r\n      </li>\r\n      ",568,1214);
$z[3][4]=array();
$z[3][4]['titlelen']="80";
$z[3][4]['orderby']="pubdate";
$z[3][4]['row']="6";
$z[4]=Array("field","",1240,1268);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("field","",1291,1320);
$z[5][4]=array();
$z[5][4]['name']="typename";

?>