<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190112/1-1Z112164U4.jpg ",93,236);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190112/1-1Z112164U4.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/190112/1-1Z112164Z5.jpg ",238,381);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190112/1-1Z112164Z5.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="599";
$z[2][4]['height']="435";

?>