<li class="team_item" > <a href="[field:arcurl/]" title="[field:title/]" target='_self'>
          <div class="team_img"> <img src="[field:picname/]" alt="[field:title/]"> </div>
          <div class="wrap">
            <div><span class="h"></span><span class="v"></span></div>
          </div>
          </a>
          <div class="team_info">
            <p class="title">[field:title/]</p>
            <p class="subtitle">[field:shorttitle/]</p>
            <p class="desc">[field:description function="cn_substr(@me,320)"/]...</p>
          </div>
        </li>