<?php
$z[0]=Array("arcurl","",33,48);
$z[0][4]=array();
$z[1]=Array("title","",57,71);
$z[1][4]=array();
$z[2]=Array("picname","",133,149);
$z[2][4]=array();
$z[3]=Array("title","",156,170);
$z[3][4]=array();
$z[4]=Array("title","",380,394);
$z[4][4]=array();
$z[5]=Array("shorttitle","",432,451);
$z[5][4]=array();
$z[6]=Array("description","",485,535);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,320)";

?>