<?php
$z[0]=Array("arclist","\r\n        <div class=\"team_item\"   > <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"\"></a>\r\n          <div class=\"team_cont\">\r\n            <p class=\"team_title\">[field:title/]</p>\r\n            <p class=\"team_keywords\">[field:shorttitle/]</p>\r\n            <p class=\"team_desc\">[field:description function=\"cn_substr(@me,180)\"/]...</p>\r\n            <a href=\"[field:arcurl/]\" class=\"team_more\">MORE</a> </div>\r\n        </div>\r\n        ",202,726);
$z[0][4]=array();
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="6";
$z[0][4]['typeid']="15";

?>