<div class="met-index-team met-index-body">
  <div class="team_bg"> <img src="/skin/img/1484739112.jpg" class="bg_img">
    <div class="container ">
      <div class="slider" id="exampleResponsive"> {dede:arclist titlelen=80 orderby ='pubdate' row='6' typeid='15'}
        <div class="team_item"   > <a href="[field:arcurl/]"><img src="[field:picname/]" alt=""></a>
          <div class="team_cont">
            <p class="team_title">[field:title/]</p>
            <p class="team_keywords">[field:shorttitle/]</p>
            <p class="team_desc">[field:description function="cn_substr(@me,180)"/]...</p>
            <a href="[field:arcurl/]" class="team_more">MORE</a> </div>
        </div>
        {/dede:arclist} </div>
    </div>
  </div>
</div>