<?php
$z[0]=Array("field","",162,191);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",322,353);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",482,514);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n        <li  style=''> \r\n		<img  alt=\"[field:typename/]\" src=\"[field:typeimg/]\"  style='width:320px; height:200px;'/>\r\n		<a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",681,934);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[4]=Array("arclist","\r\n     <!-- <div data-type=\"list_113\" style=\"width: 335px; float:left;display:black;\" >\r\n        <div class=\"widget widget-shadow\">\r\n          <figure class=\"widget-header cover\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>\r\n            <div class=\"mask\"> </div>\r\n            <img class=\"img-responsive\" alt=\"[field:title/]\" src=\"[field:picname/]\" /> </a> </figure>\r\n			<h4 class=\"widget-title\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>[field:title/]</a>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n          </h4>\r\n        </div>\r\n      </div>\r\n      ",1132,1819);
$z[4][4]=array();
$z[4][4]['titlelen']="80";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",1889,1917);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",1952,1980);
$z[6][4]=array();
$z[6][4]['name']="typeurl";

?>