<div class="met-index-product met-index-body">
  <div class="container">
	<h3 class="invisible" data-plugin="appear" data-animate="fade" data-repeat="false">{dede:field name='typename'/}</h3>
	
	<div class="met-banner " data-height='300||'>
  <div class="slick-slide"> <img class="cover-image" src="/skin/img/banner{dede:field.typeid function="gettoptype(@me,id)"/}.jpg" srcset='/skin/img/banner{dede:field.typeid function="gettoptype(@me,id)"/}.jpg' sizes="(max-width: 767px) 500px" alt="">
    <div class="banner-text p-5">
      <div class='container'>
        <div class='banner-text-con'>
          <div>
            <h1 style="color:;">{dede:field name='typename'/}</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </div>
  </div>