<?php
$z[0]=Array("field","",159,188);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",320,370);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['function']="gettoptype(@me,id)";
$z[2]=Array("field","",400,450);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['function']="gettoptype(@me,id)";
$z[3]=Array("field","",652,681);
$z[3][4]=array();
$z[3][4]['name']="typename";

?>