<?php
$z[0]=Array("field","",162,191);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",322,353);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",482,514);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",675,820);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[4]=Array("field","",866,894);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("field","",929,957);
$z[5][4]=array();
$z[5][4]['name']="typeurl";

?>