<div data-type="list_113" >
        <div class="widget widget-shadow">
          <figure class="widget-header cover"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>
            <div class="mask"> </div>
            <img class="img-responsive" alt="[field:title/]" src="[field:picname/]" style='337px; float:left;'/> </a> </figure>
			<h4 class="widget-title"> <a href="[field:arcurl/]" title="[field:title/]" target='_self' style='337px; float:left;'>[field:title/]</a>
            <p style='337px; float:left;'>[field:description function="cn_substr(@me,80)"/]...</p>
          </h4>
        </div>
      </div>