<?php
$z[0]=Array("field","",162,191);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",322,353);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",483,515);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n      <div class=\"service_item\"> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\"> <img class=\"img-responsive\" alt=\"[field:typename/]\" src=\"[field:typeimg/]\" />\r\n        <h4>[field:typename/]</h4>\r\n        <p>[field:description/]</p>\r\n        </a> </div>\r\n      ",684,992);
$z[3][4]=array();
$z[3][4]['type']="son";

?>