<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190216/1-1Z216202R7.jpg ",93,237);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190216/1-1Z216202R7.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1280";
$z[1][4]['height']="720";
$z[2]=Array("img"," /uploads/allimg/190216/1-1Z216202R7-50.jpg ",239,389);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190216/1-1Z216202R7-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1280";
$z[2][4]['height']="720";
$z[3]=Array("img"," /uploads/allimg/190216/1-1Z216202R8.jpg ",391,535);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190216/1-1Z216202R8.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1280";
$z[3][4]['height']="720";
$z[4]=Array("img"," /uploads/allimg/190216/1-1Z216202R8-50.jpg ",537,687);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190216/1-1Z216202R8-50.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1280";
$z[4][4]['height']="720";

?>