<div class="team_item"   > <a href="[field:arcurl/]"><img src="[field:picname/]" alt=""></a>
          <div class="team_cont">
            <p class="team_title">[field:title/]</p>
            <p class="team_keywords">[field:shorttitle/]</p>
            <p class="team_desc">[field:description function="cn_substr(@me,180)"/]...</p>
            <a href="[field:arcurl/]" class="team_more">MORE</a> </div>
        </div>