<?php
$z[0]=Array("arclist","\r\n                <li class=\"list-group-item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>[field:title/]</a></li>\r\n                ",150,380);
$z[0][4]=array();
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="5";
$z[0][4]['flag']="c";
$z[1]=Array("field","",483,511);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("channel","\r\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              ",586,715);
$z[2][4]=array();
$z[2][4]['type']="son";

?>