<li class=" shown">
          <div class="widget widget-shadow">
            <figure class="widget-header cover"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>
              <div class="mask"> </div>
              <img class="cover-image" src="[field:picname/]" alt="[field:title/]" style='height:200px; width:350px;'> </a> </figure>
            <h4 class="widget-title"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>[field:title/]</a>
              <p>[field:description function="cn_substr(@me,80)"/]...</p>
            </h4>
          </div>
        </li>