<div data-type="list_113" class="slick-slide slick-cloned" style="width: 337px;" data-slick-index="13" aria-hidden="true" tabindex="-1" >
        <div class="widget widget-shadow">
          <figure class="widget-header cover"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>
            <div class="mask"> </div>
            <img class="img-responsive" alt="[field:title/]" src="[field:picname/]" /> </a> </figure>
			<h4 class="widget-title"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>[field:title/]</a>
            <p>[field:description function="cn_substr(@me,80)"/]...</p>
          </h4>
        </div>
      </div>