<?php
$z[0]=Array("field","",162,191);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",322,353);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",482,514);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",675,820);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[4]=Array("arclist","\r\n      \r\n      ",1016,1092);
$z[4][4]=array();
$z[4][4]['titlelen']="80";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",1162,1190);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",1225,1253);
$z[6][4]=array();
$z[6][4]['name']="typeurl";

?>