<?php
$z[0]=Array("field","",214,242);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",401,430);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",557,588);
$z[2][4]=array();
$z[2][4]['name']="typenameen";
$z[3]=Array("sql","[field:content function='cn_substr(html2text(@me),800)'/] ",876,1005);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=3";
$z[4]=Array("field","",1033,1061);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>